### ISSUE TITLE
[FR] List non-Python publicly exported symbols found in SOs

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/deloc8#1]
From @njsmith:
> Actually, speaking of this, a feature request: when scanning a wheel, can you dump a list of all publicly exported symbols found in shared objects inside the wheel, except for those that look like python extension module entry points (init<basename> or PyInit_<basename>)? In a correctly built package there should not be any such symbols, so putting them in front of people's faces will encourage good wheel hygiene :-). (They aren't necessarily a disaster -- I know numpy will fail this test right now -- but they should be fixed eventually.)

**Comment by njsmith** [comment]
Looks like github ate some text there -- should be `init<basename>` or `PyInit_<basename>`.

Further refinement (since like you said on the email list, there are valid reasons why one might want to violate the general rule) -- provide some options to whitelist additional symbols or symbol patterns from appearing in this check. The nice thing about doing it this way, instead of just having a way to disable the check altogether, is that even for projects that do want to ship some regular shared libraries they will still notice if they've accidentally started exporting more names than they intended to.

**Comment by rmcgibbo** [comment]
Do you happen to know how symbols generated by Cython for functions defined in a `.pyx` are named / decorated?

**Comment by njsmith** [comment]
IIUC Cython cdef functions are declared static and are not exported from
the .so, so it doesn't matter.
.
The exception to this is if you declare a cdef symbol "public", in which
case it is exported and its name isn't mangled at all. But this is
generally problematic for all the reasons that exporting symbols from
Python extensions is always problematic. I am not convinced that this
feature has any valid use cases.
.
(Cython's "cimport" mechanism for sharing cdef code between different
modules is a different thing entirely, and it passes through the Python to
do the actual lookup rather than using the platform linker/loader. Using
cimport to export symbols is great, and orthogonal to anything deloc8 would
need to care about.)

On Wed, Jan 13, 2016 at 4:27 PM, Robert T. McGibbon <
notifications@github.com> wrote:

> Do you happen to know how symbols generated by Cython for functions
> defined in a .pyx are named / decorated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmcgibbo/deloc8/issues/1#issuecomment-171482991>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rmcgibbo** [comment]
Okay, perfect.
